### ISSUE TITLE
Jekyll 4.0 Support

### ISSUE THREAD

**Issue by derek-adair** [jekyll-pdf/jekyll-pdf#4]
I am interested in leveraging this but I'm on jekyll 4.0.

What's the state of this project?

**Comment by derek-adair** [comment]
I've [forked ](https://github.com/derek-adair/jekyll-pdf) and added 4.0 to the gemspec.  Currently getting this error when I `bundle exec jekyll serve`:

```
NoMethodError: undefined method `data' for nil:NilClass
  /usr/local/bundle/bundler/gems/jekyll-pdf-891bc98b072b/lib/jekyll/pdf/document.rb:47:in `get_config'
  /usr/local/bundle/bundler/gems/jekyll-pdf-891bc98b072b/lib/jekyll/pdf/document.rb:26:in `initialize'
  /usr/local/bundle/bundler/gems/jekyll-pdf-891bc98b072b/lib/jekyll/pdf/generator.rb:9:in `new'
  /usr/local/bundle/bundler/gems/jekyll-pdf-891bc98b072b/lib/jekyll/pdf/generator.rb:9:in `block in generate'
  /usr/local/bundle/bundler/gems/jekyll-pdf-891bc98b072b/lib/jekyll/pdf/generator.rb:8:in `each'
  /usr/local/bundle/bundler/gems/jekyll-pdf-891bc98b072b/lib/jekyll/pdf/generator.rb:8:in `generate'
  /usr/local/bundle/gems/jekyll-4.0.0/lib/jekyll/site.rb:185:in `block in generate'
  /usr/local/bundle/gems/jekyll-4.0.0/lib/jekyll/site.rb:183:in `each'
  /usr/local/bundle/gems/jekyll-4.0.0/lib/jekyll/site.rb:183:in `generate'
  /usr/local/bundle/gems/jekyll-4.0.0/lib/jekyll/site.rb:75:in `process'
  /usr/local/bundle/gems/jekyll-4.0.0/lib/jekyll/command.rb:28:in `process_site'
  /usr/local/bundle/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:65:in `build'
  /usr/local/bundle/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:36:in `process'
  /usr/local/bundle/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
  /usr/local/bundle/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `each'
  /usr/local/bundle/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
  /usr/local/bundle/gems/jekyll-4.0.0/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
  /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /usr/local/bundle/gems/jekyll-4.0.0/exe/jekyll:15:in `<top (required)>'
  /usr/local/bundle/bin/jekyll:29:in `load'
  /usr/local/bundle/bin/jekyll:29:in `<top (required)>'
```

Literally my first ruby code written so we'll see how this goes! :)

**Comment by derek-adair** [comment]
I'm getting this error on a freshly built Jekyll 3.8 site as well. I'm thinking it has something to do w/ my configuration.

**Comment by MauricioMoraes** [comment]
I'd love that too.

For now I've forked the project and just removed the jekyll 3.1 dependency on the gemspec. 
If I get wkhtmltopdf to work on docker with jekyll I'll try it out and see if it works with jekyll 4 or what are the limitations. 

More on that soon. (if you have something ready for docker with jekyll 4 and wkhtmltopdf let me know)
